parameters:
#    g_book.example.class: Learn\Bundle\GBookBundle\Example

services:
#    g_book.example:
#        class: %g_book.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
