<?php

namespace Film\Bundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FilmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilmRepository extends EntityRepository
{
    public function getFilmsByParams(Array $params){
        $query = $this->createQueryBuilder('f');
        foreach ($params as $param => $value) {
            $query->where(
                $query->expr()->eq("f.$param", $value)
            );
        }

        return $query->getQuery()->getResult();
    }
}
